import RPi.GPIO as GPIO

def clean():
    GPIO.cleanup()
    GPIO.setwarnings(False)
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(3,GPIO.IN)
    GPIO.setup(5,GPIO.IN)
    GPIO.setup(7,GPIO.IN)
    GPIO.setup(11,GPIO.IN)
    GPIO.setup(12,GPIO.IN)
    GPIO.setup(13,GPIO.IN)
    GPIO.setup(15,GPIO.IN)
    GPIO.setup(16,GPIO.OUT)
    GPIO.output(16,GPIO.LOW)
    GPIO.setup(18,GPIO.OUT)
    GPIO.output(18,GPIO.LOW)
    GPIO.setup(19,GPIO.IN)
    GPIO.setup(21,GPIO.IN)
    GPIO.setup(22,GPIO.IN)
    GPIO.setup(23,GPIO.IN)
    GPIO.setup(24,GPIO.OUT)
    GPIO.output(24,GPIO.LOW)
    GPIO.setup(26,GPIO.OUT)
    GPIO.output(26,GPIO.LOW)
    #GPIO.cleanup()
